### PR TITLE
Replace multiple telemetry with TelemetryPacket for faster updates

### PR DESCRIPTION
**Pull request by NoahBres**
Replace the graphing functions with telemetry packets instead of the multiple telemetry. Telemetry packets are fired at a much higher frequency by default resulting in a better graph resolution. There isn't much of a benefit to printing the graphing data to the RC telemetry anyways.

### CODE REVIEW

**Comment by NoahBres** [comment]
https://cdn.discordapp.com/attachments/225451520911605765/659185469770301441/Screen_Shot_2019-12-24_at_7.05.51_PM.png

This one is from the default Multiple Telemetry.

image

Just replacing Multiple Telemetry with Telemetry Packet.

**Comment by NoahBres** [comment]
I might be able to get more objective measures in the future but I do not have access to a bot right now.

**Comment by rbrott** [comment]
The first screenshot seems a bit outdated. There was a bug in `MultipleTelemetry` (fixed in https://github.com/acmerobotics/ftc-dashboard/commit/badfc909bad8c32ba31099f5ae4139782a613bdb, v0.3.7+) that's likely to blame.

**Comment by NoahBres** [comment]
Ah. I'm seeing it now. Just compared an older version to double check and the bug is indeed fixed. I was just used to old advice. My apologies. 😅

**Pull request closed without merging**
