### PR TITLE
Fix building with the latest Android Studio

### PR DESCRIPTION
**Pull request by qwertychouskie**
Allows building with Android Studio Ladybug, see https://github.com/FIRST-Tech-Challenge/FtcRobotController/issues/1174 for details.

### CODE REVIEW

**Comment by j5155** [comment]
It is perfectly possible to build with Android Studio Ladybug, you just have to change the Java version to Java 17. 
I would say this should be done at an SDK level, not here.

**Comment by rbrott** [comment]
Thanks for the patch. I'm a little wary of merging it and hopefully there will be an official update soon given the wide effect on teams. In the meantime, there's this [alternate solution](https://ftc-community.firstinspires.org/t/unable-to-connect-to-control-hub-in-android-studio-ladybug/1132/5?u=cmacfarlane) and I'll leave this open if anyone wants to cherry-pick it.

**Comment by qwertychouskie** [comment]
For anyone looking to apply this patch themselves, download this as a `.patch` file:

https://patch-diff.githubusercontent.com/raw/acmerobotics/road-runner-quickstart/pull/421.patch (right-click -> Save As)

Next, in Android Studio, go to the Git menu, then Patch, then Apply Patch.  Select the patch file you saved, and you are golden.

**Comment by qwertychouskie** [comment]
Closing in favor of the new SDK 10.1.1 release, see https://community.firstinspires.org/android-studio-2024.2.1-ladybug-update-and-the-first-tech-challenge-sdk

**Pull request closed without merging**
